# <div dir=rtl> מבוא למדעי הנתונים - תרגול
<div dir=rtl>מתרגלת: דניאל מילר <br />
   עוזרת הוראה: הגר רוזנבלט </div>

<div dir=rtl> 
    <br />
תרגילי בית: ארבעה תרגילי בית במהלך הסמסטר
</div>

    
# <div dir=rtl> תרגול ראשון - מבוא לפייתון </div>
<div dir=rtl> 
בתרגול זה נרענן את היסודות של תכנות בפייתון ואיך משתמשים במחברות של ג'ופיטר.
    בכתיבת מחברת, בכל שלב אפשר ללחוץ על המקש H בשביל קיצורי דרך. 
</div>
    
## <div dir=rtl> מחברת ג׳ופיטר </div>
<div dir=rtl> 
מסמך המשלב כתיבת קוד יחד עם אלמנטים טקסטואלים (לדוגמה פסקאות טקסט, משוואות ואפילו תרשימים ויזואלים)
   ניתן להשתמש במחברות בכדי לקרוא ולהבין אנליזות, ויחד עם זאת להריץ את קטע הקוד שייצר אותן. <br /><br />
    קיימות דרכים נוספות לכתוב ולתעד קוד (בפייתון וגם כל שפה אחרת), אבל מחברות כאלו שימושיות במיוחד כדי להשתמש בפייתון באופן אינטרקטיבי, להציג מידע ולהעבירו בין אנשים. 
<div dir=rtl> 
 
</div>

<div dir="rtl"> 
    הדרך הבסיסית ביותר להריץ קוד בפייתון היא על ידי הרצת קובץ בעל סיומת py.
    כך תראה דוגמת הרצה של הקובץ <code>hello_something.py</code> <br />
</div>


![](1.1.png "Python program start and end")

<br />

<div dir="rtl">
    בכדי לטעון מחברת ג׳ופיטר כל מה שצריכים לעשות הוא להיכנס לשורת הפקודה ולהריץ את הפקודה: <br />
    <code>jupyter notebook</code> <br /><br />
     לחיצה כפולה על המלל תחשוף בפניכם איך יוצרים אותו. לחיצה על Ctrl+Enter תהפוך אותו למסוגנן שוב.<br /> 
    אפשר לסגנן ולעצב את המלל בדרכים נוספות בלינק הבא: 
    <a>https://www.markdownguide.org/basic-syntax/</a>
</div>


## <div dir=rtl> רענון פייתון </div>
<div dir=rtl> 
    1. משתנים וסוגי משתנים  <br />
    2. פונקציות  <br />
    3. מחלקות  <br />
    4. חבילות  <br />
<div dir=rtl> 


In [87]:
x = 'world'

In [88]:
print(f'Hello {x}')

Hello world


In [89]:
x = 'internet'

In [93]:
print(f'Hello {x}')

Hello tel aviv


In [91]:
x = 'tel aviv'

In [92]:
print(f'Hello {x}')

Hello tel aviv


<div dir="rtl"> 
    כאן יכול להיות עוד הרבה קוד.....<br />
    <br />
    ... אבל x עדיין קיים בסביבה.
    <br />
    <br />
</div>

## <div dir=rtl>משתנים</div>

<div dir="rtl"> 
    על התאים למטה נעבור ברצף על ידי לחיצות מרובות על <br />
    Shift + Enter
</div>


In [94]:
v = 3
type(v)

int

In [95]:
v = 3.0
type(v)

float

In [96]:
v = '3'
type(v)

str

In [97]:
v = "3"
type(v)

str

In [98]:
v = '3.'
v2 = '14159...'

v3 = v + v2
v3

'3.14159...'

In [99]:
v2

'14159...'

<div dir="rtl"> 
    שימו לב שהתאים האחרונים לא הסתיימו עם print. <br />
    תא שמסתיים במשתנה - ערכו יוחזר.
</div>


In [100]:
print(v3)

3.14159...


In [101]:
v = [x,3.14159,v2,v3]
v

['tel aviv', 3.14159, '14159...', '3.14159...']

In [102]:
type(v)

list

In [104]:
v[0]

'tel aviv'

<div dir="rtl"> 
    מכאן עיקרון חשוב - אינדקסים בפייתון מתחילים באפס!<br />
    עוד נקודה מעניינת - מחרוזות בפייתון מתנהגות כמו רשימות - מחרוזות הן איטרביליות:
</div>


In [105]:
print(v3)
print(v3[0])
print(v3[1])
print(v3[2])
print(v3[3:])

3.14159...
3
.
1
4159...


<div dir="rtl"> 
    מילון הוא מבנה נתונים הממפה בין מפתח לערך כלשהו. <br />
    אפשר להגדיר מילון על ידי הפונקציה dict או על ידי יצירת משתנה עם סוגריים מסולסלים
</div>


In [106]:
x = {}
type(x)

dict

In [107]:
x = dict()
type(x)

dict

<div dir="rtl"> 
    השמת זוג מפתח-ערך לתוך מילון:
</div>


In [108]:
x['This is the first key'] = 'this is the first value'
x

{'This is the first key': 'this is the first value'}

In [109]:
x['This is the second key'] = 2
x

{'This is the first key': 'this is the first value',
 'This is the second key': 2}

In [110]:
# what will happen here?
x[3] = 'This is the third key'
x

{'This is the first key': 'this is the first value',
 'This is the second key': 2,
 3: 'This is the third key'}

In [111]:
# what will be printed?
x[['This','is','the',4,'th','key']] = 5

TypeError: unhashable type: 'list'

<div dir="rtl"> 
    יכולת חשובה מאוד בתכנות היא חיפוש באגים בגוגל! <br />
    חיפוש קצר הביא אותנו לאתר השימושי 
    stackoverflow.com 
    שם מישהו קיבל *בדיוק* את אותה השגיאה. 
    מישהו אחר ענה לו בטוב ליבו - שלא ניתן להשתמש ברשימות בתור מפתחות במילון. 
    צריך מבנה נתונים אחר - כזה שברגע שהוא נוצר בזיכרון לא ניתן לערוך אותו אלא רק ליצור אחד חדש - הוא immutable. <br />
    מבנה הנתונים הזה הוא הטאפל
</div>




In [112]:
x[('This','is','the',4,'th','key')] = 4
x

{'This is the first key': 'this is the first value',
 'This is the second key': 2,
 3: 'This is the third key',
 ('This', 'is', 'the', 4, 'th', 'key'): 4}

<div dir="rtl"> 
    למילונים יש פונקציות שימושיות נלוות שלא יהיה לנו זמן לדון בהן. <br />
    get() keys() values() items()... <br />
    <a>https://docs.python.org/3/library/stdtypes.html#typesmapping</a>
</div>



## <div dir=rtl>פונקציות</div>

<div dir="rtl"> 
    קטע קוד שרץ רק כשקוראים לו. על פונקציה מכריזים עם התחילית def.
</div>


In [113]:
def first_function():
    return "Hello from a function"

<div dir="rtl"> 
    מריצים את הבלוק ו..... לא קורה כלום. הפונקציה תרוץ רק כשיקראו לה.
</div>


In [114]:
first_function()

'Hello from a function'

<div dir="rtl"> 
    משתנה שהוכרז בגוף הקוד המרכזי יהיה זמין בכל פונקציה, אבל לא להפך:
</div>

In [115]:
this_is_a_global_variable = 3.14159

def second_function():
    return this_is_a_global_variable
    
second_function()

3.14159

<div dir="rtl"> 
    אבל
</div>

In [116]:
def third_function():
    this_is_NOT_a_global_variable = 2.718
    

third_function()

print(this_is_NOT_a_global_variable)

NameError: name 'this_is_NOT_a_global_variable' is not defined

<div dir="rtl"> 
    מה שהוגדר בתוך פונקציה לא זמין מחוץ לה. <br /> 
    כדי לייצא ערכים מתוך פונקציה מחזירים אותם:
</div>

In [117]:
def Nth_function():
    this_is_not_a_global_variable = 2.718

    return this_is_not_a_global_variable

Nth_function()

2.718

<div dir="rtl"> 
    לפונקציה אפשר להכניס ערכים בתור פרמטרים. <br />
    למטה מוצגות כמה דרכים שונות ושימושיות.
</div>

In [120]:
def Nth_function(a,b,c):
    return a*b*c

Nth_function(1,3,1e3)

3000.0

In [121]:
def Nth_function(*argv):
    '''
    argv is a list.
    By the way - this is how you write multi-line comments...
    '''
    output = 1
    
    for arg in argv:
        output *= arg
    
    return output

Nth_function(1,3,1e3)

(1, 3, 1000.0)


3000.0

In [86]:
def Nth_function(**keyword_arguments):
    '''
    keyword_arguments (or kwargs) is a dict
    '''
    a = keyword_arguments['a']
    b = keyword_arguments['b']
    c = keyword_arguments['c']
    
    return a*b*c


Nth_function(a=1, b=3, c=1e3, d="what is d?", e='last name')

{'a': 1, 'b': 3, 'c': 1000.0, 'd': 'what is d?', 'e': 'last name'}


3000.0

## <div dir=rtl>מחלקות - class</div>

<div dir="rtl"> 
    פייתון היא שפה מונחית עצמים. מחלקה מגדירה טיפוס אופייני - הקלאס - ולו פונקציות ששייכות לו ומאפיינים שלו. אחרי שהגדרנו את הטיפוס האופייני, מגדירים אובייקטים ששייכים לאותו הטיפוס - instance: 
</div>

In [34]:
class bad_guy:
    # This is an empty class
    # By the way - this is how you write single line comments.
    pass


thanos = bad_guy()

type(thanos)

__main__.bad_guy

<div dir="rtl"> 
    thanos הוא instance של מלחקה bad_guy. <br />
    לאוביקט יש מתודה - methods - פונקציה השייכת למחלקה.
    מתודה מגדירים כמו פונקציה רק בתוך המחלקה ועם הארגומנט self.
    מתודה חשובה היא __init__ שרצה כשהאובייקט נוצר.

</div>

In [35]:
class good_guy:
    def __init__(self, last_name):
        self.last_name = last_name
    
    def what_is_your_name(self):
        return self.last_name
    

IM = good_guy('Stark')
print(f'Mr {IM.what_is_your_name()}, I dont feel so good...')

Mr Stark, I dont feel so good...


<div dir="rtl"> 
    כאן הגדרנו משתנה מחלקה בשם last_name.
    כל מתודה מתנהג כמו פונקציה - משתנה שנוצר בתוכה נהרס כשהמתודה מסיימת. 
    משתנה מחלקה מוגדר על ידי self ויהיה זמין מכל נקודה במחלקה אחרי שהוא נוצר. <br />
    הפונקציה what_is_you_name היא מתודה משום שהיא מוגדרת על ידי self. 

</div>

# <div dir=rtl> חבילות - numpy </div>
<div dir=rtl> 
    חבילות הן קטע קוד חיצוני שנכתב בפייתון. חבילות הופכות את התכנות למודולרי - הן מאפשרות שבירה של קוד ארוך ומתוכחם לכמה קבצים ולתיקיות, כך שניתן לסדר את הקוד לפי היררכיה או מחלקות שונות או כל דרך שנבחר.<br /> 
    נתחיל בחבילה שימושית לכל קוד מתמטי - NumPy.
</div>


In [123]:
import numpy as np

<div dir=rtl> 
    הסיומת as np היא לנוחות בלבד.
</div>

In [124]:
np.__version__

'1.20.0'

<div dir=rtl> 
    מה עושים עם נאמפיי? דבר שימושי בג'ופיטר הוא שיש דוקומנטציה מובנית:
</div>

In [125]:
np?

<div dir=rtl> 
    ניצור מטריצה כלשהי ונבדוק את המאפיינים שלה.
</div>

In [126]:
x = np.zeros((3,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<div dir=rtl> 
    כל מטריצה היא אובייקט נאמפיי שעבורו יש את המאפיינים הבאים:
    <br />ndim - מספר המימדים של המטריצה
    <br />shape - הגודל של כל מימד
    <br />size - מספר האיברים במטריצה
</div>

In [127]:
print(x.ndim)
print(x.shape)
print(x.size)

2
(3, 4)
12


In [128]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div dir=rtl> 
אם אנחנו לא מכירים את הפונקציה eye, הדרך הטובה ביותר היא פשוט לחפש אותה בגוגל
</div>

<div dir=rtl> 
    לכל מטריצה יש פרמטר נוסף - dtype - הקובע אילו ערכים יכולים להיות בכל תא ("מעל איזה שדה המטריצה מוגדרת")
</div>

 - np.int8
 - np.int16
 - np.int32
 - np.float32
 - np.bool_
 - np.string_ (S1, S2, ..... S100, ... )
 - np.object
 - ...

In [129]:
x.dtype

dtype('float64')

In [43]:
x.astype?

## <div dir=rtl> Indexing </div>
<div dir=rtl>
    פעולות חיתוך מתוחכמות יכולות לחסוך מאיתנו ריבוי שורות קוד וחישובים מיותרים. <br />
    האינדקסים בנאמפיי הולכים לפי האינדקסים המוכרים מאלגברה לינארית

</div>

![](2.1.png)

In [130]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [131]:
x = x.reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
row = 2
column = 2
x[row,column]

8

In [133]:
x[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [134]:
x[::-1,::-1]

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

<div dir=rtl>
    נאמפיי יודע גם לחתוך לפי בוליאנים:
</div>

In [135]:
x<5

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]])

In [136]:
x[x<5]

array([0, 1, 2, 3, 4])